const express = require('express');
const { body, validationResult } = require('express-validator');
const { auth, authorize } = require('../middleware/auth');

const router = express.Router();

// @route   POST /api/reports/generate
// @desc    Generate fleet reports
// @access  Private (Admin only)
router.post('/generate', auth, authorize('admin'), [
  body('type')
    .notEmpty()
    .withMessage('Report type is required')
    .isString(),
  body('includedMetrics')
    .optional()
    .isArray()
    .withMessage('includedMetrics must be an array'),
  body('dateRange.start')
    .optional()
    .isISO8601()
    .withMessage('Start date must be in ISO8601 format'),
  body('dateRange.end')
    .optional()
    .isISO8601()
    .withMessage('End date must be in ISO8601 format')
], async (req, res) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        message: 'Validation failed',
        errors: errors.array()
      });
    }

    const { type, includedMetrics = [], dateRange = {} } = req.body;

    console.log(`📊 Report Generated: Report type "${type}" generated by admin ${req.user.username}`);

    res.status(200).json({
      success: true,
      message: 'Report generated successfully',
      data: {
        type,
        includedMetrics,
        dateRange,
        generatedBy: req.user._id,
        downloadUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800',
        createdAt: new Date()
      }
    });
  } catch (error) {
    console.error('Generate report error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while generating report'
    });
  }
});

module.exports = router;
